### ISSUE TITLE
No new streams

### ISSUE THREAD

**Issue by Pizzaluvr** [CommanderRoot/twitch-tools#12] opened 2022-06-02 02:17 UTC
No streams are appearing when sorted by "Just started --> Long online"

**Comment by bxssl** [comment] 2022-06-02 18:01
@Pizzaluvr The issue seems to have been fixed now

**Comment by Pizzaluvr** [comment] 2022-06-03 04:46
The issue seems to be present still, nothing updates and only see livestreams that have been finished for over 14 hours

**Comment by bxssl** [comment] 2022-06-03 06:27
@Pizzaluvr Just checked and yeah the issue is still there my bad, it seems that it's not only the "Just started --> Long online" filter that has the problem, the whole twitch stream filter on the site no longer shows streams that are under 15 hours or something, I don't know what's up with that, hope it gets fixed soon

**Comment by CommanderRoot** [comment] 2022-06-04 19:20
This issue is related to a continues [DDOS attack](https://twitter.com/CommanderRoot/status/1533159612144312321) which is happening for about a week but only really caused issues the past 3 days.
Basically the script updating this data times out and aborts after a certain number of failed requests. Sometimes this means no update at all (stale data) or it means just getting a few top streams and missing low viewer ones.

**Closed as completed by CommanderRoot** 2022-06-04 19:20 UTC
