### ISSUE TITLE
Please check the status of my ID

### ISSUE THREAD

**Issue by lotes880147** [CommanderRoot/twitch-tools#68] opened 2023-12-07 11:19 UTC
"I'm not sure if I've been labeled as a robot again.
Please check the status of my ID [akagi__1925].
This has happened for the second time. Can you explain the method of determination?
Being banned leads to the disappearance of the tracking date.
The live stream channel I tracked in 2015 was auto-banned.
This is very frustrating for me."

**Comment by CommanderRoot** [comment] 2023-12-07 14:37
Duplicate of #30

There is no account with the name `akagi__1925`. There is one with the name `akagi_1925` and that one isn't on my "known bots" list since it got removed via #65

**Closed as completed by CommanderRoot** 2023-12-07 14:37 UTC
Labels: duplicate
