### ISSUE TITLE
Hello my name is mondkarotte on Twitch and I'm not a bot :))

### ISSUE THREAD

**Issue by mondkarotte** [CommanderRoot/twitch-tools#91] opened 2024-05-22 20:37 UTC

**Comment by CommanderRoot** [comment] 2024-05-22 20:41
Duplicate of #30

Your account was added to the list on `2022-07-21` as it was part of one or multiple follow bot raids, for example against [keronkes](https://www.twitch.tv/keronkes).
Either way it happend I have now removed you from the list

**Closed as completed by CommanderRoot** 2024-05-22 20:41 UTC
Labels: duplicate
