### ISSUE TITLE
I know this guy

### ISSUE THREAD

**Issue by Yourpalduke** [CommanderRoot/twitch-tools#88] opened 2024-05-11 16:20 UTC
![Screenshot 2024-05-11 120139](https://github.com/CommanderRoot/twitch-tools/assets/169547403/86454a22-50ac-4059-9cf4-8ec046c20cdf)

Twitch user leontheicecreamlucario is listed as a known bot.  I know the guy, he's in a couple discord servers of friends of mine.  He isn't a bot.

**Comment by CommanderRoot** [comment] 2024-05-11 16:22
Duplicate of #30 

The account was added to the list on `2022-09-25` as it was used for follow botting. It's quite likely that it was compromised at that time. Either way it happened I have now removed it from the list

**Closed as completed by CommanderRoot** 2024-05-11 16:22 UTC
Labels: duplicate
