### ISSUE TITLE
Question about a "reported bot"

### ISSUE THREAD

**Issue by ZatosPotatoes** [CommanderRoot/twitch-tools#64] opened 2023-10-11 11:03 UTC
![image](https://github.com/CommanderRoot/twitch-tools/assets/75025222/9bb2510c-9a92-4ba8-9ab5-a88003a16c90)
I have a couple questions as to how it could've happened that this person (a friend of mine) got flagged as a bot and if there is any way to reverse it. Ge never did anything wrong and never showed behavior that is similar to a bot.

**Comment by CommanderRoot** [comment] 2023-10-11 14:36
Duplicate of #30

The account in question got added to the known bot list on 2021-07-21. It was part of a follow bot raid against the channels demon_230_, cet1223 and joch_floude. It's quite possible that it was compromised back then.
Either way I have now removed it from the list. If you find other accounts you can try to look them up with my tools and then use the "Report" option on the bottom of the "Account info" area to report and account as "a bot" or "not a bot"

**Closed as completed by CommanderRoot** 2023-10-11 14:36 UTC
Labels: duplicate
