### ISSUE TITLE
Please remove my tag as soon as possible

### ISSUE THREAD

**Issue by lotes880147** [CommanderRoot/twitch-tools#65] opened 2023-10-26 07:42 UTC
![image](https://github.com/CommanderRoot/twitch-tools/assets/135326242/35e6ce83-91f3-48a4-a703-86815e8d3f61)
"I don't know why my account has been categorized as a (BOT),
but I am not a (BOT). Please help me remove the tag.
You have already caused me trouble, and my following of streamers has been forcibly unfollowed.
Please remove my tag as soon as possible."

**Comment by CommanderRoot** [comment] 2023-10-26 09:37
Duplicate of #30.

Your account was added to the list on 2022-06-26 because it was part of a follow bot raid agaist `sh4dysidex` and `zxcensored`. It's possible that it was compromised back then.
Either way I have now removed it from the list

**Closed as completed by CommanderRoot** 2023-10-26 09:37 UTC
Labels: duplicate
