### ISSUE TITLE
One of my users gets banned as soon as he follows

### ISSUE THREAD

**Issue by Jersus9426** [CommanderRoot/twitch-tools#99] opened 2024-09-05 10:55 UTC
HI! One of my followers (name: tommibaro) is constantly banned as soon as he releases the follow. I tried to remove the restriction manually but the ban comes back every time. Is there any way to fix this? He's someone dear to me so I wouldn't want him to be banned. Can I somehow report him as a ''real person''?

**Comment by CommanderRoot** [comment] 2024-09-05 11:32
> HI! One of my followers (name: tommibaro) is constantly banned as soon as he releases the follow. I tried to remove the restriction manually but the ban comes back every time. Is there any way to fix this? He's someone dear to me so I wouldn't want him to be banned. Can I somehow report him as a ''real person''?

Duplicate of #30 

The account was added to the known bot list on `2021-12-03` as it was part of a follow bot raid against [diazdead](https://www.twitch.tv/diazdead). It's possible that the account was compromised back then. Either way it happened I have now removed the account from the list

**Closed as completed by CommanderRoot** 2024-09-05 11:32 UTC
Labels: duplicate
