### ISSUE TITLE
Blocklist 'sync' app?

### ISSUE THREAD

**Issue by ToeiRei** [CommanderRoot/twitch-tools#32] opened 2023-01-03 18:23 UTC
The blocklist for known bots is getting huge. To sync it efficiently, is there a way to do that with a local app or service to cut down load times?

**Comment by CommanderRoot** [comment] 2023-01-04 03:44
Duplicate of #4. Sadly the way the Twitch API works at this time doesn't really allow for accurate caching the current state of blocks

**Closed as completed by CommanderRoot** 2023-01-04 03:44 UTC
