### ISSUE TITLE
[Unblock request] please remove my account from bot account list

### ISSUE THREAD

**Issue by huphia** [CommanderRoot/twitch-tools#76] opened 2024-01-07 20:06 UTC
Hello, my twitch username is 'huphia'. Recently twitch banned my account because some bot hacked my account and spam messages were sent. But after asking twitch, they unbanned me after a day. I think my username is added into your bot account list because I cannot watch some streamers nor follow them, even though some are new to me. Please check the list and remove my username from it. I am not a bot, my account was just hacked. Hope you can remove my username, thankyou.

**Comment by CommanderRoot** [comment] 2024-01-07 20:11
Duplicate of #30 

Your account was added to the list on 2021-04-28 as it was part of one or multiple follow bot raids. Either way it happened I have now removed it from the list.

**Closed as completed by CommanderRoot** 2024-01-07 20:11 UTC
Labels: duplicate, help wanted

**Comment by huphia** [comment] 2024-01-08 05:58
How long does it take to get unblocked by other streamers? I still see some streams blocked for me.

**Comment by CommanderRoot** [comment] 2024-01-08 06:00
Removing your account will only prevent further blocks. All streamers which have blocked your account will have to manually unblock you

**Comment by huphia** [comment] 2024-01-08 07:40
Sigh, so there wasn't much point to the request then. What an irresponsible tool, yikes.

**Comment by CommanderRoot** [comment] 2024-01-08 07:43
Of course there is a point to get your account removed. As I said it prevents it from be blocked by even more users

**Comment by huphia** [comment] 2024-01-08 08:02
Yes, that's why I said 'not much point'. Damage has already been done by your tool, which doesn't even let the user know, and you are doing nothing to rectify it properly. I guess minority always get rekt.
