### ISSUE TITLE
Non of the bots are removed

### ISSUE THREAD

**Issue by Wolfie2121** [CommanderRoot/twitch-tools#39] opened 2023-03-03 22:27 UTC
Lately we are getting bot spammed 4 times per stream
We are using commanderroot to remove the bots, when pushing the remove button it show it is deleting the bots, but after checking the users none of them are deleted.

**Comment by CommanderRoot** [comment] 2023-03-03 23:18
Duplicate of https://github.com/CommanderRoot/twitch-tools/issues/38#issuecomment-1440965437

**Closed as completed by CommanderRoot** 2023-03-03 23:18 UTC
