### ISSUE TITLE
My Account was banned because it was compromised

### ISSUE THREAD

**Issue by Harley2787** [CommanderRoot/twitch-tools#31] opened 2023-01-02 23:21 UTC
Hi, my account was banned a while ago by twitch because It was compromised then used in a raid. I now have my account back and wonder if its possible to get my account removed from the bot list

harley2707 is the username of my twitch account
![image](https://user-images.githubusercontent.com/83428883/210284422-bf63fef0-a87b-4eb4-b048-fff685d64b41.png)

**Comment by CommanderRoot** [comment] 2023-01-02 23:28
I have removed your account. Duplicate of #30

**Closed as completed by CommanderRoot** 2023-01-02 23:28 UTC
